package com.projekt.easyfly;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HelpRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Description of the problem")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Customer email ")
	private java.lang.String customerEmail;
	@org.kie.api.definition.type.Label("Problem priority")
	private java.lang.Integer priority;

	public HelpRequest() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(java.lang.String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public HelpRequest(java.lang.String description,
			java.lang.String customerEmail, java.lang.Integer priority) {
		this.description = description;
		this.customerEmail = customerEmail;
		this.priority = priority;
	}

}