package com.projekt.easyfly;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class License implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "LincenseID")
	private java.lang.String lincenseID;
	@org.kie.api.definition.type.Label(value = "valid until")
	private java.lang.Integer validYear;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	public License() {
	}

	public java.lang.String getLincenseID() {
		return this.lincenseID;
	}

	public void setLincenseID(java.lang.String lincenseID) {
		this.lincenseID = lincenseID;
	}

	public java.lang.Integer getValidYear() {
		return this.validYear;
	}

	public void setValidYear(java.lang.Integer validYear) {
		this.validYear = validYear;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public License(java.lang.String lincenseID, java.lang.Integer validYear,
			java.lang.String name) {
		this.lincenseID = lincenseID;
		this.validYear = validYear;
		this.name = name;
	}

}