package com.projekt.easyfly;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Payment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String holder;
	private int expiry;
	private java.math.BigInteger number;

	public Payment() {
	}

	public java.lang.String getHolder() {
		return this.holder;
	}

	public void setHolder(java.lang.String holder) {
		this.holder = holder;
	}

	public int getExpiry() {
		return this.expiry;
	}

	public void setExpiry(int expiry) {
		this.expiry = expiry;
	}

	public java.math.BigInteger getNumber() {
		return this.number;
	}

	public void setNumber(java.math.BigInteger number) {
		this.number = number;
	}

	public Payment(java.lang.String holder, int expiry,
			java.math.BigInteger number) {
		this.holder = holder;
		this.expiry = expiry;
		this.number = number;
	}

}