package com.projekt.easyfly;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelPlanDesign implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("who is the plan for? families/singles/couples...")
	private java.lang.String intendedCustomer;
	@org.kie.api.definition.type.Label("Destination")
	private java.lang.String destination;
	@org.kie.api.definition.type.Label("maximum price")
	private java.lang.Integer price;
	@org.kie.api.definition.type.Label("Duration of the plan")
	private java.lang.Integer duration;

	public TravelPlanDesign() {
	}

	public java.lang.String getIntendedCustomer() {
		return this.intendedCustomer;
	}

	public void setIntendedCustomer(java.lang.String intendedCustomer) {
		this.intendedCustomer = intendedCustomer;
	}

	public java.lang.String getDestination() {
		return this.destination;
	}

	public void setDestination(java.lang.String destination) {
		this.destination = destination;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public TravelPlanDesign(java.lang.String intendedCustomer,
			java.lang.String destination, java.lang.Integer price,
			java.lang.Integer duration) {
		this.intendedCustomer = intendedCustomer;
		this.destination = destination;
		this.price = price;
		this.duration = duration;
	}

}